[package]
name = "postgres-openssl"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "openssl support for the postgres crate"
categories = ["database"]

[dependencies]
openssl = "0.10.9"

postgres = { version = "0.15", path = "../postgres" }
